Write-Host "=== Testing Deactivate/Reactivate Persistence with Debug Logging ==="
Write-Host ""
Write-Host "1. Clear debug log"
$debugLog = "$env:USERPROFILE\Documents\MRT-UI\debug.log"
if (Test-Path $debugLog) {
    Remove-Item $debugLog
    Write-Host "   ✓ Cleared debug.log" -ForegroundColor Green
}

Write-Host ""
Write-Host "2. Start the app"
Write-Host "   - Enable MRT-1"
Write-Host "   - Set Shift Ring = ON"
Write-Host "   - Check: Shift ring is visible"
Write-Host ""
Write-Host "3. Click Deactivate button"
Write-Host "   - Widget should hide"
Write-Host ""
Write-Host "4. Click Activate button"
Write-Host "   - Widget should reappear"
Write-Host "   - CHECK: Is Shift Ring still ON?"
Write-Host ""
Write-Host "5. Close the app"
Write-Host ""
Write-Host "After test, run: Get-Content '$debugLog' -Tail 50"
Write-Host ""
Write-Host "Look for:"
Write-Host "  - [WidgetManager] GetSavedWidgetConfig: Found config..."
Write-Host "  - [OverlayVM] IsActive: Using saved config..."
Write-Host "  - [MRTOne] LoadSettings: Config.Settings has X entries"
Write-Host ""
